name: Staging
values:
  - key: baseUrl
    value: 'https://api.staging.prodreach.com'
    enabled: true
    type: default
  - key: openai_api_base_url
    value: 'https://api.openai.com/v1'
    enabled: true
    type: default
  - key: base_model_name
    value: gpt-4o-mini
    enabled: true
    type: default
  - key: agent_model_name
    value: gpt-4o
    enabled: true
    type: default
  - key: text_embedding_model_name
    value: text-embedding-3-small
    enabled: true
    type: default
  - key: mongo_uri
    value: ''
    enabled: true
    type: secret
  - key: db_name
    value: prodreach
    enabled: true
    type: default
  - key: openai_api_key
    value: ''
    enabled: true
    type: secret
